version: 1
loggers:
  root:
    level: DEBUG
    handlers: [console]
formatters:
  brief:
    format: "%(levelname)-8s %(name)-15s %(message)s"
  default:
    format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
